<?xml version="1.0"?>    
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">    
    
  <xacro:macro name="custom_four_wheel_base" params="prefix">    
    <!-- 标量变量 -->
    <xacro:property name="chassis_zero_height" value="0.09" />
    <xacro:property name="chassis_length" value="0.41" />
    <xacro:property name="chassis_width" value="0.4" />
    <xacro:property name="chassis_height" value="0.2" />

    <xacro:property name="driver_x_offset" value="-0.15" />
    <xacro:property name="driver_y_offset" value="0.19" />
    <xacro:property name="driver_radius" value="0.0675" />
    <xacro:property name="caster_x_offset" value="0.15" />
    <xacro:property name="caster_y_offset" value="0.08" />
    <xacro:property name="caster_radius" value="0.025" />

    <xacro:property name="chassis_heart_x_offset" value="0" />
    <xacro:property name="chassis_heart_y_offset" value="0" />
    <xacro:property name="chassis_heart_z_offset" value="-0.05" />

    <xacro:property name="caster_z_offset" value="${driver_radius - caster_radius}" />

    <xacro:property
    name="meshes_file_direction"
    value="package://turtlebot3_manipulation_description/meshes/turtlebot3_waffle_pi"/>
          
    <!-- Base footprint -->    
    <link name="${prefix}base_footprint"/>    
        
    <!-- Base link -->    
    <joint name="${prefix}base_joint" type="fixed">    
      <parent link="${prefix}base_footprint"/>    
      <child link="${prefix}base_link"/>    
      <origin xyz="0.0 0.0 ${driver_radius}" rpy="0 0 0"/>    
    </joint>   

    <link name="${prefix}base_link">    
      <visual>    
        <origin xyz="0 0 ${chassis_zero_height+chassis_height/2-driver_radius}" rpy="0 0 0"/>    
        <geometry>    
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>    
        </geometry>    
        <material name="transparent_black">    
          <color rgba="0 0 0 0.5"/>    
        </material>    
      </visual>   
          
      <collision>    
        <origin xyz="0 0 ${chassis_zero_height+chassis_height/2-driver_radius}" rpy="0 0 0"/>    
        <geometry>    
          <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>    
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="${chassis_heart_x_offset} ${chassis_heart_y_offset} ${chassis_zero_height+chassis_height/2-driver_radius+chassis_heart_z_offset}" rpy="0 0 0"/>    
        <mass value="10.0"/>    
        <inertia ixx="0.2708" ixy="0.0" ixz="0.0"    
                  iyy="0.2708" iyz="0.0"    
                  izz="0.2667"/>    
      </inertial>    
    </link>    

    <joint name="${prefix}center_of_mass_joint" type="fixed">  
      <parent link="${prefix}base_link"/>  
      <child link="${prefix}center_of_mass_link"/>  
      <origin xyz="${chassis_heart_x_offset} ${chassis_heart_y_offset} ${chassis_zero_height+chassis_height/2-driver_radius+chassis_heart_z_offset}" rpy="0 0 0"/>  
    </joint>    

    <link name="${prefix}center_of_mass_link">  
      <visual>  
        <origin xyz="0 0 0" rpy="0 0 0"/>  
        <geometry>  
          <sphere radius="0.02"/>  
        </geometry>  
        <material name="red">  
        </material>  
      </visual>  
    </link>  
    
    <!-- Left drive wheel -->    
    <joint name="${prefix}wheel_left_joint" type="continuous">    
      <parent link="${prefix}base_link"/>    
      <child link="${prefix}wheel_left_link"/>    
      <origin xyz="${driver_x_offset} ${driver_y_offset} 0" rpy="-1.57 0 0"/>    
      <axis xyz="0 0 1"/>    
    </joint>    
    
    <link name="${prefix}wheel_left_link">    
      <visual>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="${driver_radius}" length="0.03"/>    
        </geometry>    
        <material name="black"/>     
      </visual>    
          
      <collision>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="${driver_radius}" length="0.03"/>    
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <mass value="0.2"/>    
        <inertia ixx="0.00114" ixy="0.0" ixz="0.0"    
                  iyy="0.00114" iyz="0.0"    
                  izz="0.00228"/>    
      </inertial>    
    </link>    
    
    <!-- Right drive wheel -->    
    <joint name="${prefix}wheel_right_joint" type="continuous">    
      <parent link="${prefix}base_link"/>    
      <child link="${prefix}wheel_right_link"/>    
      <origin xyz="${driver_x_offset} ${-driver_y_offset} 0" rpy="-1.57 0 0"/>    
      <axis xyz="0 0 1"/>    
    </joint>    
    
    <link name="${prefix}wheel_right_link">    
      <visual>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="${driver_radius}" length="0.03"/>    
        </geometry>    
        <material name="black"/>     
      </visual>    
          
      <collision>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="${driver_radius}" length="0.03"/>    
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <mass value="0.2"/>    
        <inertia ixx="0.00114" ixy="0.0" ixz="0.0"    
                  iyy="0.00114" iyz="0.0"    
                  izz="0.00228"/>    
      </inertial>    
    </link>    

    <joint name="${prefix}caster_front_left_joint" type="fixed">    
      <parent link="${prefix}base_link"/>    
      <child link="${prefix}caster_front_left_link"/>    
      <origin xyz="${caster_x_offset} ${caster_y_offset} 0" rpy="0 0 0"/>
    </joint>    

    <joint name="${prefix}caster_front_right_joint" type="fixed">    
      <parent link="${prefix}base_link"/>    
      <child link="${prefix}caster_front_right_link"/>    
      <origin xyz="${caster_x_offset} ${-caster_y_offset} 0" rpy="0 0 0"/>  
    </joint>

    <joint name="${prefix}caster_connector_left_joint" type="fixed">    
      <parent link="${prefix}base_link"/>    
      <child link="${prefix}caster_connector_left_link"/>    
      <origin xyz="${caster_x_offset} ${caster_y_offset} 0" rpy="0 0 0"/>
    </joint>    

    <joint name="${prefix}caster_connector_right_joint" type="fixed">    
      <parent link="${prefix}base_link"/>    
      <child link="${prefix}caster_connector_right_link"/>    
      <origin xyz="${caster_x_offset} ${-caster_y_offset} 0" rpy="0 0 0"/>  
    </joint>

    <link name="${prefix}caster_connector_left_link">
      <!-- 添加固定连杆 -->
      <visual>    
        <origin xyz="0 0 ${chassis_zero_height/2-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="0.005" length="${chassis_zero_height-2*caster_radius}"/>    
        </geometry>    
        <material name="black">    
          <color rgba="0.0 0.0 0.0 1.0"/>    
        </material>      
      </visual>
          
      <collision>    
        <origin xyz="0 0 ${chassis_zero_height/2-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="0.005" length="${chassis_zero_height-2*caster_radius}"/>   
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="0 0 ${chassis_zero_height/2-caster_z_offset}" rpy="0 0 0"/>    
        <mass value="0.1"/>    
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0"    
                  iyy="0.00001" iyz="0.0"    
                  izz="0.00001"/>    
      </inertial>    
    </link>

    <link name="${prefix}caster_front_left_link">
      <!-- 添加固定连杆 -->     
      <visual>    
        <origin xyz="0 0 ${-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <sphere radius="${caster_radius}"/>    
        </geometry>    
        <material name="black">    
          <color rgba="0.0 0.0 0.0 1.0"/>    
        </material>      
      </visual>    
          
      <collision>    
        <origin xyz="0 0 ${-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <sphere radius="${caster_radius}"/>    
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="0 0 ${-caster_z_offset}" rpy="0 0 0"/>    
        <mass value="0.1"/>    
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0"    
                  iyy="0.00001" iyz="0.0"    
                  izz="0.00001"/>    
      </inertial>    
    </link>

    <link name="${prefix}caster_connector_right_link">
      <!-- 添加固定连杆 -->
      <visual>    
        <origin xyz="0 0 ${chassis_zero_height/2-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="0.005" length="${chassis_zero_height-2*caster_radius}"/>    
        </geometry>    
        <material name="black">    
          <color rgba="0.0 0.0 0.0 1.0"/>    
        </material>      
      </visual>
          
      <collision>    
        <origin xyz="0 0 ${chassis_zero_height/2-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="0.005" length="${chassis_zero_height-2*caster_radius}"/>   
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="0 0 ${chassis_zero_height/2-caster_z_offset}" rpy="0 0 0"/>    
        <mass value="0.1"/>    
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0"    
                  iyy="0.00001" iyz="0.0"    
                  izz="0.00001"/>    
      </inertial>    
    </link>

    <link name="${prefix}caster_front_right_link">
      <!-- 添加固定连杆 -->     
      <visual>    
        <origin xyz="0 0 ${-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <sphere radius="${caster_radius}"/>    
        </geometry>    
        <material name="black">    
          <color rgba="0.0 0.0 0.0 1.0"/>    
        </material>      
      </visual>    
          
      <collision>    
        <origin xyz="0 0 ${-caster_z_offset}" rpy="0 0 0"/>    
        <geometry>    
          <sphere radius="${caster_radius}"/>    
        </geometry>    
      </collision>    
          
      <inertial>    
        <origin xyz="0 0 ${-caster_z_offset}" rpy="0 0 0"/>    
        <mass value="0.1"/>    
        <inertia ixx="0.00001" ixy="0.0" ixz="0.0"    
                  iyy="0.00001" iyz="0.0"    
                  izz="0.00001"/>    
      </inertial>    
    </link>

    <joint name="${prefix}imu_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}imu_link"/>
      <origin xyz="0.0 0 ${chassis_zero_height-driver_radius-0.01}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}imu_link">
      <visual>    
        <origin xyz="0 0 0" rpy="0 0 0"/>    
        <geometry>    
          <cylinder radius="0.03" length="0.02"/>       
        </geometry>    
        <material name="black">    
          <color rgba="0.0 0.0 0.0 1.0"/>    
        </material>    
      </visual>   
    </link> 

    <joint name="${prefix}scan_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base_scan"/>
      <origin xyz="${chassis_length/2-0.08} 0 ${chassis_zero_height-driver_radius+chassis_height+0.01}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}base_scan">
      <visual>
        <origin xyz="0 0 0.0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${meshes_file_direction}/ladar.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="dark"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${meshes_file_direction}/ladar.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                iyy="0.001" iyz="0.0"
                izz="0.001" />
      </inertial>
    </link>

    <joint name="${prefix}camera_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}camera_link"/>
      <origin xyz="${chassis_length/2+0.01} 0 ${chassis_zero_height-driver_radius+chassis_height-0.01}" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}camera_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.03 0.02"/>
        </geometry>
        <material name="dark"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.03 0.02"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}camera_rgb_joint" type="fixed">
      <parent link="${prefix}camera_link"/>
      <child link="${prefix}camera_rgb_frame"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${prefix}camera_rgb_frame"/>

    <joint name="${prefix}camera_rgb_optical_joint" type="fixed">
      <parent link="${prefix}camera_rgb_frame"/>
      <child link="${prefix}camera_rgb_optical_frame"/>
      <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    </joint>

    <link name="${prefix}camera_rgb_optical_frame"/>
    
  </xacro:macro>    
    
</robot>